include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
    invalid_use_of_protected_member: error
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    must_call_super: error
    parameter_assignments: error
    sort_unnamed_constructors_first: ignore
  exclude:
    - lib/*.config.dart
    - lib/**/*.g.dart
    - lib/**/*.gr.dart
    - lib/**/*.freezed.dart

linter:
  rules:
    omit_local_variable_types: true
    prefer_relative_imports: true
    prefer_single_quotes: true
    sort_pub_dependencies: true
